[Bot_1]
	Type = "QQ"
	AccessToken = ""
	APIEndpoint = ""
	Secret = ""

[Bot_2]
	Type = "Telegram"
	Token = ""

[HTTPServer]
	Domain = ""

[Database]
	User = ""
	Password = ""
	DBName = ""

[Test]
	Test = true